"""Generates app/src/render_census.cpp: a counting wrapper around every entry
point of the Xbox D3D library (d3d_layer.json from d3d_layer.py).

Each guest function sub_X is a weak alias of __imp__sub_X; defining sub_X in
the app replaces it for every caller, and __imp__sub_X stays the original.
The wrappers only count and call the original once. With --render_census=true
the log gets, every 300 frames (frame = calls of the VdSwap caller), each
entry's calls per frame and the arguments/return address of its last call.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
layer = json.load(open(os.path.join(HERE, "d3d_layer.json")))
g = json.load(open(os.path.join(HERE, "callgraph.json")))
entries = [e[0] for e in layer["entries"]]
swap = next(f for f in entries if "VdSwap" in g[f]["imports"])

out = []
out.append("""// GENERATED by tools/renderprobe/gen_census.py - do not edit.
// Counting wrappers around the entry points of the statically linked Xbox D3D
// library (render census for the native renderer feasibility study).
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>
#include <algorithm>

#include <rex/cvar.h>
#include <rex/logging.h>
#include <rex/ppc/context.h>
#include <rex/ppc/func.h>

REXCVAR_DEFINE_BOOL(render_census, false, "Debug",
                    "Count calls into the game's D3D library and log them every 300 frames");

namespace {
struct CensusEntry {
  const char* name;
  std::atomic<uint64_t> calls{0};
  std::atomic<uint32_t> r3{0}, r4{0}, r5{0}, r6{0}, lr{0};
};
""")
out.append(f"constexpr int kEntries = {len(entries)};")
out.append("CensusEntry g_entries[kEntries] = {")
for f in entries:
    out.append(f'  {{"{f}"}},')
out.append("};")
out.append("""
inline void Count(int i, PPCContext& ctx) {
  CensusEntry& e = g_entries[i];
  e.calls.fetch_add(1, std::memory_order_relaxed);
  e.r3.store(ctx.r3.u32, std::memory_order_relaxed);
  e.r4.store(ctx.r4.u32, std::memory_order_relaxed);
  e.r5.store(ctx.r5.u32, std::memory_order_relaxed);
  e.r6.store(ctx.r6.u32, std::memory_order_relaxed);
  e.lr.store(static_cast<uint32_t>(ctx.lr), std::memory_order_relaxed);
}

void Report() {
  static uint64_t frames = 0;
  if (++frames % 300) return;
  struct Row { int i; uint64_t n; };
  std::vector<Row> rows;
  for (int i = 0; i < kEntries; ++i) {
    uint64_t n = g_entries[i].calls.exchange(0, std::memory_order_relaxed);
    if (n) rows.push_back({i, n});
  }
  std::sort(rows.begin(), rows.end(), [](const Row& a, const Row& b) { return a.n > b.n; });
  std::string s;
  for (const Row& r : rows) {
    const CensusEntry& e = g_entries[r.i];
    char buf[200];
    std::snprintf(buf, sizeof(buf), "\\n  %s %9.2f/frame  r3=%08X r4=%08X r5=%08X r6=%08X lr=%08X",
                  e.name, r.n / 300.0, e.r3.load(), e.r4.load(), e.r5.load(), e.r6.load(),
                  e.lr.load());
    s += buf;
  }
  REXLOG_INFO("[render census] 300 frames, {} entry points used:{}", rows.size(), s);
}
}  // namespace
""")
for i, f in enumerate(entries):
    out.append(f'extern "C" REX_FUNC(__imp__{f});')
    out.append(f'extern "C" REX_FUNC({f}) {{')
    out.append(f"  if (REXCVAR_GET(render_census)) {{")
    out.append(f"    Count({i}, ctx);")
    if f == swap:
        out.append("    Report();")
    out.append("  }")
    out.append(f"  __imp__{f}(ctx, base);")
    out.append("}")
path = os.path.join(HERE, "..", "..", "app", "src", "render_census.cpp")
open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print(f"{len(entries)} wrappers, frame boundary {swap} -> {os.path.normpath(path)}")
